title: Recording a video with a Raspberry Pi and Camera Module
hero_image: 
description: Record video with the Camera Module
theme: red
duration: 1
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2018-03-26"
curriculum: 
interests: 
technologies: 
hardware: 
software: 
site_areas: projects
steps:
  - title: Recording a video with a Raspberry Pi and Camera Module

